"""add current_team_ratings table

Revision ID: 1382ac19cf0b
Revises: e78d3116c57c
Create Date: 2026-07-31 20:30:17.829616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1382ac19cf0b'
down_revision: Union[str, Sequence[str], None] = 'e78d3116c57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('attack_rating', sa.Float(), nullable=False),
    sa.Column('defence_rating', sa.Float(), nullable=False),
    sa.Column('form_rating', sa.Float(), nullable=False),
    sa.Column('last_match_date', sa.Date(), nullable=True),
    sa.Column('last_season', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'model_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_team_ratings')
    # ### end Alembic commands ###
