"""multi-source match identity and expanded player stats

Revision ID: 1e852c4047f6
Revises: d1106f20b323
Create Date: 2026-07-30 14:22:16.993896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e852c4047f6'
down_revision: Union[str, Sequence[str], None] = 'd1106f20b323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_source_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_match_id', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_source', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_by_source_match_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(
            'uq_matches_season_date_home_away',
            ['season_year', 'match_date', 'home_team_id', 'away_team_id'],
        )
        batch_op.drop_column('source_match_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inside_50s', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rebound_50s', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clangers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frees_for', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frees_against', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brownlow_votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contested_marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marks_inside_50', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('one_percenters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bounces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_assists', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('goal_assists')
        batch_op.drop_column('bounces')
        batch_op.drop_column('one_percenters')
        batch_op.drop_column('marks_inside_50')
        batch_op.drop_column('contested_marks')
        batch_op.drop_column('brownlow_votes')
        batch_op.drop_column('frees_against')
        batch_op.drop_column('frees_for')
        batch_op.drop_column('clangers')
        batch_op.drop_column('rebound_50s')
        batch_op.drop_column('inside_50s')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('source_match_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_matches_season_date_home_away', type_='unique')
        batch_op.drop_column('created_by_source_match_id')
        batch_op.drop_column('created_by_source')

    op.drop_table('match_source_refs')
    # ### end Alembic commands ###
