"""add final_league_avg_score to model_versions

Revision ID: b57cf4f6686b
Revises: 1382ac19cf0b
Create Date: 2026-07-31 20:32:52.882604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57cf4f6686b'
down_revision: Union[str, Sequence[str], None] = '1382ac19cf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_league_avg_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_column('final_league_avg_score')

    # ### end Alembic commands ###
