"""initial schema

Revision ID: d1106f20b323
Revises: 
Create Date: 2026-07-30 13:26:59.768651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1106f20b323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_player_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_player_id')
    )
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_datetime', sa.DateTime(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('home_behinds', sa.Integer(), nullable=True),
    sa.Column('home_points', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('away_behinds', sa.Integer(), nullable=True),
    sa.Column('away_points', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('weather_temp_c', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_match_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_match_id')
    )
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'alias_name')
    )
    op.create_table('venue_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'alias_name')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('home_decimal_odds', sa.Float(), nullable=True),
    sa.Column('away_decimal_odds', sa.Float(), nullable=True),
    sa.Column('home_line', sa.Float(), nullable=True),
    sa.Column('away_line', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker', 'snapshot_type')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('disposals', sa.Integer(), nullable=True),
    sa.Column('kicks', sa.Integer(), nullable=True),
    sa.Column('handballs', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('behinds', sa.Integer(), nullable=True),
    sa.Column('hitouts', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('contested_possessions', sa.Integer(), nullable=True),
    sa.Column('uncontested_possessions', sa.Integer(), nullable=True),
    sa.Column('time_on_ground_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_winner_team_id', sa.Integer(), nullable=False),
    sa.Column('predicted_margin', sa.Float(), nullable=False),
    sa.Column('predicted_line', sa.Float(), nullable=False),
    sa.Column('predicted_total', sa.Float(), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['predicted_winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'model_version_id')
    )
    op.create_table('team_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inside_50s', sa.Integer(), nullable=True),
    sa.Column('contested_possessions', sa.Integer(), nullable=True),
    sa.Column('uncontested_possessions', sa.Integer(), nullable=True),
    sa.Column('contested_marks', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('hitouts', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('disposals', sa.Integer(), nullable=True),
    sa.Column('kicks', sa.Integer(), nullable=True),
    sa.Column('handballs', sa.Integer(), nullable=True),
    sa.Column('frees_for', sa.Integer(), nullable=True),
    sa.Column('frees_against', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('intercepts', sa.Integer(), nullable=True),
    sa.Column('metres_gained', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id')
    )
    op.create_table('team_rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.Column('attack_rating', sa.Float(), nullable=True),
    sa.Column('defence_rating', sa.Float(), nullable=True),
    sa.Column('form_rating', sa.Float(), nullable=True),
    sa.Column('travel_adjustment', sa.Float(), nullable=True),
    sa.Column('rest_adjustment', sa.Float(), nullable=True),
    sa.Column('injury_adjustment', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'model_version_id')
    )
    op.create_table('team_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('was_named', sa.Boolean(), nullable=False),
    sa.Column('was_played', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'player_id')
    )
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('winner_correct', sa.Boolean(), nullable=True),
    sa.Column('margin_error', sa.Float(), nullable=True),
    sa.Column('total_error', sa.Float(), nullable=True),
    sa.Column('closing_line_diff', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_results')
    op.drop_table('team_selections')
    op.drop_table('team_rating_history')
    op.drop_table('team_match_stats')
    op.drop_table('predictions')
    op.drop_table('player_match_stats')
    op.drop_table('odds')
    op.drop_table('venue_aliases')
    op.drop_table('team_aliases')
    op.drop_table('matches')
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('players')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
