"""add league_avg_score_before to team_rating_history

Revision ID: e69b9054d91e
Revises: b57cf4f6686b
Create Date: 2026-07-31 20:47:35.490564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69b9054d91e'
down_revision: Union[str, Sequence[str], None] = 'b57cf4f6686b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_rating_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_avg_score_before', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_rating_history', schema=None) as batch_op:
        batch_op.drop_column('league_avg_score_before')

    # ### end Alembic commands ###
