"""add team home location for travel adjustment

Revision ID: e78d3116c57c
Revises: 1e852c4047f6
Create Date: 2026-07-31 14:49:01.716575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78d3116c57c'
down_revision: Union[str, Sequence[str], None] = '1e852c4047f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('home_longitude')
        batch_op.drop_column('home_latitude')
        batch_op.drop_column('home_city')

    # ### end Alembic commands ###
